### ISSUE TITLE
add support for "client connected" callback for Snowflake Proxy

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/IPtProxy#13]
applications that are running a snowflake proxy want to know how many people they are helping!

**Comment by tladesignz** [comment]
@bitmold, @n8fr8, is that suitable for you? I don't have a setup to test this, so your feedback is highly appreciated!

**Comment by bitmold** [comment]
I'm content with how this was implemented. In an Android service I've made which wraps IPtProxy I am using the callback successfully there, and it's used in a rudimentary way in Orbot at the moment.
