### ISSUE TITLE
update to latest snowflake

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/IPtProxy#15]
anti-fingerprinting changes made

see: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/40014

**Comment by tladesignz** [comment]
Updated to Snowflake 2.0.1 in 2e67e8d9e34a44c1490c7e34d534f91fd750d287

@bitmold, can you please test in Orbot? Esp. Snowflake Proxy start/stop has changed a lot.

**Comment by bitmold** [comment]
This issue might be worth revisiting for snowflake 2.1.0 


> +- Issue 40098: Remove support for legacy one shot mode
+- Issue 40079: Make connection summary at proxy privacy preserving
+- Issue 40076: Add snowflake event API for notifications of connection events
+- Issue 40084: Increase capacity of client address map at the server
+- Issue 40060: Further clean up snowflake server logs
+- Issue 40089: Validate proxy and client supplied strings at broker
+- Issue 40014: Update version of DTLS library to include fingerprinting fixes
+- Issue 40075: Support recurring NAT type check in standalone proxy

Among other things, there's an official event API that IPtProxy should be using

**Comment by bitmold** [comment]
My mistake on this, it looks like these callbacks are for the client, not for hosting a proxy

**Comment by tladesignz** [comment]
All your suggested changes available for your enjoyment: https://jitpack.io/#tladesignz/IPtProxy/1.5.0

**Comment by tladesignz** [comment]
(Snowflake now at 2.1.0)
