### ISSUE TITLE
Support Snowflake 2.2.0 

### ISSUE THREAD

**Issue by bitmold** [tladesignz/IPtProxy#25]
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commit/ae5a71e6e58e664311e3a12f9adb48ed439df4a5 a new release !

**Comment by tladesignz** [comment]
Thank you very much! Implemented with 553cf5f9c6a2d9591bc0c19882cb7b3df950688e

**Comment by tladesignz** [comment]
Looking good: https://jitpack.io/#tladesignz/IPtProxy
