### ISSUE TITLE
Modify snowflake client start() function with new arguments

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/IPtProxy#32]
we need to add utls-imitate and fingerprint arguments to the start() method in snowflake client, since we cannot provide those values via command line or socks arguments.

see: https://gitweb.torproject.org/pluggable-transports/snowflake.git/tree/client/snowflake.go?h=v2.3.1#n107

**Comment by tladesignz** [comment]
Aha. No. Sorry, these are *PER CONNECTION* arguments. They are handed over via Tor. You configure them at the `Bridge` line:

See

https://gitweb.torproject.org/torspec.git/tree/pt-spec.txt#n716

https://2019.www.torproject.org/docs/tor-manual.html.en#Bridge

In this case, the bridge line should look like this:

```
Bridge: snowflake 192.0.2.3:1 2B280B23E1107BB62ABFC40DDCC8824814F80A72 utls-imitate=[...] fingerprint=[...]
```

Can you please provide a little background on this so I can understand what this is all about and if I should add something on the iOS side and what values?

**Comment by tladesignz** [comment]
Sorry, just re-read your initial statement which confuses me. Why should you not be able to provide these values via SOCKS CONNECT arguments as lined out by me?
