### ISSUE TITLE
Snowflakr Proxy v2.5.1 Available - Changes Unclear... 

### ISSUE THREAD

**Issue by bitmold** [tladesignz/IPtProxy#36]
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/releases/v2.5.1

Oddly, the ChangeLog file only includes release notes for versions 2.4.2 and 2.4.3...

**Comment by tladesignz** [comment]
Looking at the commits, the changes are actually small and are in underlying dependencies: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/commits/main

**Comment by tladesignz** [comment]
Fixed with f2828ad4705800863d09a71a53a0af5a8d54ca29.

New release 1.10.0 coming right now.

**Comment by tladesignz** [comment]
I now tested with iOS. I don't have any issues there with Snowflake 2.5.1. Therefore, I continue with this version for now.
Let me know, as soon as you have more details about the bug on Android. If you file an issue with Tor Project, please link it here!
