### ISSUE TITLE
Experimental Snowflake Proxy stop patch

### ISSUE THREAD

**Issue by tladesignz** [tladesignz/IPtProxy#4]
@n8fr8, please check out ae7608141f6fd9c9acbcfb82420b960f9e7ee06f in the [feature/stop_snowflake_proxy](https://github.com/tladesignz/IPtProxy/tree/feature/stop_snowflake_proxy) branch.

I have no idea how to test this in real life currently, but the logic per se should be good.

Might be, that it takes a while until all concurrent clients are gone and also might be that there are some recreated. Let me know if this is good already, or it needs to improve!

**Comment by n8fr8** [comment]
testing this now!

**Comment by tladesignz** [comment]
Now contained in release 0.6.0!
