### ISSUE TITLE
Why does IPtProxy tell Snowflake Proxy to log to stderr

### ISSUE THREAD

**Issue by bitmold** [tladesignz/IPtProxy#40]
```go
			logOutput = io.MultiWriter(os.Stderr, f)
```

can it please be stdio?

**Comment by tladesignz** [comment]
No idea. Copied from Snowflake? Changed!

**Comment by bitmold** [comment]
Thanks - it was slightly annoying looking at error logs and seeing random snowflake diagnostic info there too
