### ISSUE TITLE
Update x/net and x/crypto to latest version

### ISSUE THREAD

**Issue by syphyr** [tladesignz/IPtProxy#45]
For security purposes, golang.org/x/crypto and golang.org/x/net should be updated to latest versions.  This also requires the obfs4 and snowflake submodules to do the same thing, so there needs to be some coordination between all three projects for this to happen.

https://github.com/syphyr/IPtProxy/commit/80f7c728cbc1144f2ab29634fbe2a58e8d62def8

**Comment by tladesignz** [comment]
I let Tor know:
https://gitlab.torproject.org/tpo/anti-censorship/team/-/issues/122

Let's wait and see.

Thank you for reporting!

**Comment by meskio** [comment]
I think this can be closed, let me know if something is missing in our side.

**Comment by syphyr** [comment]
Yes, this can be closed. Although, this change has not been as added to the new fork yet.
