### ISSUE TITLE
goptlib has new gitlab location

### ISSUE THREAD

**Issue by bitmold** [tladesignz/IPtProxy#46]
Canonically goptlib now lives at [gitlab.torproject.org](http://gitlab.torproject.org/).

> If you want to use it at the new location, change this import:
	import "[git.torproject.org/pluggable-transports/goptlib.git](http://git.torproject.org/pluggable-transports/goptlib.git)"
to this:
	import "[gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/goptlib](http://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/goptlib)"
and then run `go get` and `go mod tidy`.

More info here: https://gitlab.torproject.org/tpo/anti-censorship/team/-/issues/86#note_2823122

The old url that IPtProxy uses will continue to work, but probably not forever ... 

~
Best :+)

**Comment by tladesignz** [comment]
Hmmmm. Why should we patch Snowflake and Obfs4proxy instead of wait on Tor Project do change it when they're ready?

**Comment by bitmold** [comment]
I was never suggesting that... I thought iptproxy directly used goptlib but upon further inspection it does not . My mistake

-------- Original Message --------

**Comment by tladesignz** [comment]
Ah, ok. Thanks! No worries!
