### ISSUE TITLE
[Question]Where to view func obfs4proxy.start

### ISSUE THREAD

**Issue by vegedove** [tladesignz/IPtProxy#47]
Hi, Where to view the obfs4proxy.start function (in the func startobfs4proxy)? I checked the yawning/obfs4 project source but did not find this function. Thank you :)

**Comment by tladesignz** [comment]
Admitted, it's not obvious, if one doesn't want to try hunting it down by actually reading about how to build this project oneself in the [README.md](https://github.com/tladesignz/IPtProxy/blob/master/README.md#build).

But if so, that would lead one to [build.sh](https://github.com/tladesignz/IPtProxy/blob/d616d67c7a0841986eb2dcbbe828271448a85008/build.sh#L57) and that would lead to [obfs4.patch](https://github.com/tladesignz/IPtProxy/blob/d616d67c7a0841986eb2dcbbe828271448a85008/obfs4.patch#L68) and that would answer this question. 😗
