### ISSUE TITLE
Use snowflake from gitlab.torproject.org

### ISSUE THREAD

**Issue by meskio** [tladesignz/IPtProxy#48]
We are in the process of deprecating git.torproject.org. Snowflake now uses gitlab.torproject.org for development.

We'll try to make it work, so git.torproject.org urls keep working. But will be nice if IPtProxy could use gitlab.torproject.org instead.

Sorry for the repos reorganization.

**Comment by tladesignz** [comment]
No worries! Thanks for letting me know!
