### ISSUE TITLE
Issue with Snowflake on Android 11+

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/IPtProxy#51]
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/40278

**Comment by n8fr8** [comment]
We need an update IPtProxy with latest fix merged as indicated on the ticket above please!

**Comment by tladesignz** [comment]
Fixed with 6963a3a6bd001c2f72f8a551199937d1baf83c04.
Already uploaded to Sonatype.
Will appear [there](https://central.sonatype.com/artifact/com.netzarchitekten/IPtProxy) soon.
