### ISSUE TITLE
IPtProxy-0.5.2.jar file not find error?

### ISSUE THREAD

**Issue by tongmunujf** [tladesignz/IPtProxy#52]
* What went wrong:
Could not determine the dependencies of task ':app:lint'.
> Could not resolve all artifacts for configuration ':app:releaseRuntimeClasspath'.
   > Could not find IPtProxy-0.5.2.jar (com.github.tladesignz:IPtProxy:0.5.2).
     Searched in the following locations:
         https://jitpack.io/com/github/tladesignz/IPtProxy/0.5.2/IPtProxy-0.5.2.jar

**Comment by tladesignz** [comment]
See https://github.com/tladesignz/IPtProxy#installation-1

Please switch to the Maven Central source!

**Comment by tongmunujf** [comment]
My local code is as follows：
dependencies {
    implementation(name:'IPtProxy', ext:'aar')
    implementation 'com.netzarchitekten:IPtProxy:3.1.0'
    //implementation 'com.github.tladesignz:IPtProxy:3.1.0'
    /*相册  implementation 'com.github.LuckSiege.PictureSelector:picture_library:v2.2.3'*/
    implementation 'com.github.LuckSiege.PictureSelector:picture_library:v2.2.3'
    //implementation 'com.github.ZLYang110:FileSelector:2.1.6'
    implementation 'com.github.ZLYang110:FileSelector:1.0.2'
    implementation 'com.github.ZLYang110:UpperDialog:1.4.1'
    implementation 'com.github.imcloudfloating:ProgressBar:1.1'
    implementation 'com.github.chrisbanes:PhotoView:2.0.0'
}
repositories {
        google()
        jcenter()
        maven {
            url 'https://jitpack.io'
            content {
                includeModule('com.github.tladesignz', 'IPtProxy')
            }
        }
    }
IPtProxy.aar was downloaded from https://github.com/guardianproject/Orbot-IPtProxy/blob/master/IPtProxy.aar and imported into the libs directory of my project
But there are the following issues with writing this way：
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.LuckSiege.PictureSelector:picture_library:v2.2.3.
     Required by:
         project :app
   > Could not find com.github.ZLYang110:FileSelector:1.0.2.
     Required by:
         project :app
   > Could not find com.github.ZLYang110:UpperDialog:1.4.1.
     Required by:
         project :app
   > Could not find com.github.imcloudfloating:ProgressBar:1.1.
     Required by:
         project :app
   > Could not find com.github.chrisbanes:PhotoView:2.0.0.

**Comment by tladesignz** [comment]
Don't mix downloaded AArs with a dependency of the same lib on Maven Central.

There's other error messages about libraries of yours.

Sorry, this is not a programming course.
