### ISSUE TITLE
Snowflake 2.8.1 Was Released

### ISSUE THREAD

**Issue by bitmold** [tladesignz/IPtProxy#55]
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/blob/main/ChangeLog?ref_type=heads

**Comment by tladesignz** [comment]
Lucky you! https://github.com/tladesignz/IPtProxy/blob/master/CHANGELOG.md ;-)

(But keep up the notifications, it's far from typical, that I see this before you...)
