### ISSUE TITLE
Bump Lyrebird to version 2.0 Adding Webtunnel Support 

### ISSUE THREAD

**Issue by bitmold** [tladesignz/IPtProxy#56]
https://github.com/syphyr/IPtProxy/commits/master/ If you look at Syphyr's fork here it starts the work of adding webtunnel to IPtProxy 

Looking to bring webtunnel support into a demo android app and orbot later this week so it'd be lovely to get something like this properly added into IPtProxy :))

**Comment by tladesignz** [comment]
> also, whoops, was trying to make a PR for the small text change commit I just published. i was using the online editor thinking it'd make a new PR but it committed it directly to the repo, I must have forgotten/didn't realize i had write access like that

No worries. Commit looks ok. :-)

**Comment by tladesignz** [comment]
> https://github.com/syphyr/IPtProxy/commits/master/ If you look at Syphyr's fork here it starts the work of adding webtunnel to IPtProxy
> 
> Looking to bring webtunnel support into a demo android app and orbot later this week so it'd be lovely to get something like this properly added into IPtProxy :))

Damnit! How did I overlook that 0.2.0 release of Lyrebird? I'll update. I won't merge Syphir's work, however. I want to stay on release tags, when possible.

**Comment by tladesignz** [comment]
Version 3.8.0 released containing Lyrebird 0.2.0 with Webtunnel support: https://github.com/tladesignz/IPtProxy/commits/3.8.0

**Comment by tladesignz** [comment]
Uuups. Better use version https://github.com/tladesignz/IPtProxy/commits/3.8.1
