### ISSUE TITLE
Need to make all ports dynamic

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/IPtProxy#7]

**Comment by n8fr8** [comment]
or at least app specify the port to start

**Comment by tladesignz** [comment]
Stupid me. Already forgot again, what I did 2 months ago. @bitmold was right, there is an experimental branch:
https://github.com/tladesignz/IPtProxy/tree/experiment/port_collision

It starts with one port and tests them, until it finds an open one.

I merged latest master, fixed some minor doc issues and tested, if it compiles. Works for me!
@bitmold, please try that (You'll need to compile yourself, no binaries contained.), and let me know, if this works good enough to get it in an official release!

**Comment by tladesignz** [comment]
Seems to be good enough. I'll close this.
