### ISSUE TITLE
[Question] Setting Destination obfs3 server

### ISSUE THREAD

**Issue by xtianxian** [tladesignz/IPtProxy#9]
Hi. How do i set the destination obfs3 server for android? and also how to set to use transparent-tcp instead of default transport? Or am i looking at the wrong library? Thank you

**Comment by tladesignz** [comment]
> Hi. How do i set the destination obfs3 server for android?

This is done via configuring Tor. Here is an example from Onion Browser: (That's Swift on iOS, but the configuration of Tor is the same on all platforms)

https://github.com/OnionBrowser/OnionBrowser/blob/2.X/OnionBrowser/OnionManager.swift#L58

https://github.com/OnionBrowser/OnionBrowser/blob/2.X/OnionBrowser/OnionManager.swift#L95

https://github.com/OnionBrowser/OnionBrowser/blob/2.X/OnionBrowser/OnionManager.swift#L514-L522

https://github.com/OnionBrowser/OnionBrowser/blob/2.X/OnionBrowser/OnionManager.swift#L539-L554


> and also how to set to use transparent-tcp instead of default transport? Or am i looking at the wrong library? Thank you

Sorry, no idea what you're talking about here.

**Comment by xtianxian** [comment]
Thank you!
